[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]
twilight-gateway = { version = "0.16", features = ["native-tls", "simd-json", "zlib-simd"] }

tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
